# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 17:44
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0002_sentence_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
