# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0003_auto_20170909_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='order_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
