# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0005_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='text',
        ),
        migrations.AddField(
            model_name='sentence',
            name='paragraph',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='translates.Paragraph'),
            preserve_default=False,
        ),
    ]
