# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0006_auto_20170918_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='text_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentence',
            name='text_order_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
